{
  "network": {
    "host": "127.0.0.1",
    "port": 8080,
    "disable_auth": true,
    "api_servers": [
      "OAI"
    ],
    "sse_ping_interval": 15,
    "allowed_origins": [
      "*"
    ]
  },
  "logging": {
    "log_prompt": false,
    "log_generation_params": false,
    "log_live_status": false,
    "log_chat_completion_requests": false
  },
  "model": {
    "model_dir": "/opt/llm/models",
    "model_name": "qwen3.8-27b-uncensored",
    "backend": "exllamav3",
    "inline_model_loading": false,
    "max_seq_len": 114688,
    "cache_size": 114688,
    "cache_mode": "Q8",
    "max_batch_size": 1,
    "chunk_size": 1024,
    "vision": false,
    "warmup": false,
    "tool_format": "qwen3_coder",
    "reasoning": true,
    "reasoning_start_token": "<think>",
    "reasoning_end_token": "</think>",
    "start_in_reasoning": "auto",
    "template_vars_default": {
      "enable_thinking": true
    }
  },
  "draft_model": {
    "draft_mode": "model",
    "draft_model_dir": "/opt/llm/models",
    "draft_model_name": "dflash",
    "draft_cache_mode": "Q8",
    "draft_num_tokens": 7,
    "dynamic_draft": false
  },
  "sampling": {
    "override_preset": null,
    "temperature": {
      "override": 1.0,
      "force": false
    },
    "top_k": {
      "override": 20,
      "force": false
    },
    "top_p": {
      "override": 0.95,
      "force": false
    },
    "min_p": {
      "override": 0.0,
      "force": false
    },
    "max_tokens": {
      "override": 32768,
      "force": false
    }
  },
  "memory": {
    "sysmem_recurrent_cache": 4096,
    "sysmem_kv_cache": 8192
  }
}
